# Generated by Django 2.2.3 on 2019-12-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
